name: Build Java Versionamento

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Versionamento
        run: |
          echo "Versão gerada: 1.0.${{ github.run_number }}"
          run: mvn clean package -DskipTests -Drevision=1.0.${{ github.run_number }}
