name: Build Java com versão automática

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build com versão automática
        run: |
          echo "Versão gerada: 1.0.${{ github.run_number }}"
          mvn clean package -DskipTests -Drevision=1.0.${{ github.run_number }}
